### ISSUE TITLE
dependabot PRs are failing

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/explore#1512]
See https://github.com/gemini-hlsw/explore/pull/1511

Is it maybe related to the font awesome variable?

**Comment by armanbilge** [comment]
Hmm, did these used to work? It seems that dependabot is not given access to the font awesome secret:
```
Run npm install
  npm install
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    FONTAWESOME_NPM_AUTH_TOKEN: 
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64
```
